// Vinte textos de lorem ipsum salvos em array para que serem apresentados de forma aleatoria
  const randomP = [    
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec adipiscing tristique risus nec feugiat in. Eget arcu dictum varius duis at consectetur lorem. Ac turpis egestas maecenas pharetra. Id aliquet lectus proin nibh. Enim nunc faucibus a pellentesque sit amet. Tortor at auctor urna nunc id cursus metus. Pretium nibh ipsum consequat nisl vel. Elementum curabitur vitae nunc sed velit. Vestibulum lorem sed risus ultricies tristique. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Adipiscing tristique risus nec feugiat. Sapien faucibus et molestie ac feugiat sed lectus vestibulum.",
    "In arcu cursus euismod quis viverra nibh cras pulvinar. Libero enim sed faucibus turpis in eu. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Magna ac placerat vestibulum lectus mauris ultrices. At tellus at urna condimentum mattis pellentesque. Nunc lobortis mattis aliquam faucibus purus in. Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. In metus vulputate eu scelerisque felis imperdiet proin fermentum. Porttitor eget dolor morbi non arcu risus quis varius quam. Suspendisse sed nisi lacus sed viverra. Ut sem viverra aliquet eget sit amet tellus cras. Sapien eget mi proin sed libero enim sed. Feugiat in ante metus dictum at tempor commodo ullamcorper. Amet consectetur adipiscing elit pellentesque habitant. Lacus viverra vitae congue eu consequat ac felis. Tellus pellentesque eu tincidunt tortor aliquam. Non odio euismod lacinia at quis risus sed. Integer quis auctor elit sed vulputate mi sit amet. Enim blandit volutpat maecenas volutpat.", 
    "Odio tempor orci dapibus ultrices. Urna nunc id cursus metus aliquam. Morbi tristique senectus et netus et malesuada fames. Massa placerat duis ultricies lacus sed. Adipiscing diam donec adipiscing tristique risus nec feugiat in fermentum. Vel orci porta non pulvinar neque laoreet suspendisse interdum. Consectetur adipiscing elit duis tristique sollicitudin nibh. At lectus urna duis convallis convallis tellus id interdum. Fringilla est ullamcorper eget nulla facilisi etiam. Mattis vulputate enim nulla aliquet porttitor lacus. Fermentum iaculis eu non diam phasellus vestibulum lorem sed. Feugiat vivamus at augue eget arcu. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Nulla facilisi cras fermentum odio eu feugiat pretium. Accumsan tortor posuere ac ut consequat semper viverra nam libero. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Ut tristique et egestas quis ipsum suspendisse ultrices gravida. Sit amet risus nullam eget. Et leo duis ut diam quam nulla porttitor massa id.",
    "Sapien eget mi proin sed libero. Mus mauris vitae ultricies leo integer malesuada nunc. Gravida quis blandit turpis cursus in hac habitasse platea dictumst. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Gravida dictum fusce ut placerat orci nulla. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Mattis enim ut tellus elementum sagittis. Amet massa vitae tortor condimentum lacinia quis vel eros donec. Eu scelerisque felis imperdiet proin fermentum leo vel orci porta. Tellus at urna condimentum mattis pellentesque. Risus in hendrerit gravida rutrum quisque. Neque ornare aenean euismod elementum nisi quis eleifend quam. In nibh mauris cursus mattis molestie. Porttitor leo a diam sollicitudin tempor id eu. Sapien pellentesque habitant morbi tristique senectus et netus.",
    "Semper auctor neque vitae tempus. Amet luctus venenatis lectus magna fringilla urna. Mauris augue neque gravida in fermentum et. Dui vivamus arcu felis bibendum ut. Eget felis eget nunc lobortis mattis aliquam faucibus purus in. Eget lorem dolor sed viverra ipsum nunc. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Amet consectetur adipiscing elit duis tristique sollicitudin. Pharetra diam sit amet nisl suscipit. Aliquam ultrices sagittis orci a scelerisque purus semper. Magna sit amet purus gravida. Justo donec enim diam vulputate. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Vel pretium lectus quam id. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Tortor aliquam nulla facilisi cras fermentum. Felis imperdiet proin fermentum leo.", 
    "Viverra nam libero justo laoreet sit amet. Dolor purus non enim praesent elementum. Odio morbi quis commodo odio aenean sed. Pellentesque eu tincidunt tortor aliquam. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Ut aliquam purus sit amet luctus venenatis lectus. Turpis massa sed elementum tempus. Penatibus et magnis dis parturient montes nascetur ridiculus. At tempor commodo ullamcorper a lacus vestibulum. Sollicitudin tempor id eu nisl. Turpis egestas maecenas pharetra convallis posuere morbi leo urna molestie. Euismod quis viverra nibh cras pulvinar mattis nunc sed. Mi eget mauris pharetra et ultrices neque ornare aenean. Cursus euismod quis viverra nibh cras pulvinar mattis nunc sed.",
    "Urna id volutpat lacus laoreet non curabitur. Ac tortor dignissim convallis aenean. Maecenas ultricies mi eget mauris pharetra et ultrices. Ac tincidunt vitae semper quis. Ultrices neque ornare aenean euismod elementum nisi quis eleifend. Et egestas quis ipsum suspendisse ultrices. Lectus proin nibh nisl condimentum id venenatis. Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Nulla at volutpat diam ut venenatis. Lorem sed risus ultricies tristique nulla aliquet enim tortor. Malesuada bibendum arcu vitae elementum. Sit amet massa vitae tortor condimentum lacinia quis. Facilisi cras fermentum odio eu. Sed elementum tempus egestas sed sed risus pretium quam vulputate.", 
    "Erat nam at lectus urna duis convallis. Sit amet mauris commodo quis imperdiet massa tincidunt. Sit amet tellus cras adipiscing. Tortor at risus viverra adipiscing at in tellus integer. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Praesent tristique magna sit amet purus gravida. Sapien pellentesque habitant morbi tristique. Leo urna molestie at elementum eu facilisis sed odio morbi. Viverra mauris in aliquam sem fringilla ut morbi. Velit scelerisque in dictum non. Lacus sed turpis tincidunt id aliquet risus feugiat in ante. Aliquet enim tortor at auctor urna nunc id cursus metus. Ut enim blandit volutpat maecenas volutpat. Nulla pharetra diam sit amet nisl suscipit. Diam in arcu cursus euismod. Convallis convallis tellus id interdum velit. Diam vel quam elementum pulvinar etiam non quam lacus. Consequat interdum varius sit amet mattis vulputate enim. Nisi lacus sed viverra tellus in hac habitasse. Iaculis eu non diam phasellus vestibulum lorem sed.",  
    "Quisque non tellus orci ac auctor augue mauris augue neque. Pretium viverra suspendisse potenti nullam ac. Fames ac turpis egestas integer eget aliquet nibh praesent. Urna neque viverra justo nec ultrices dui. Nunc sed blandit libero volutpat. Semper viverra nam libero justo laoreet sit. Est lorem ipsum dolor sit. Faucibus et molestie ac feugiat sed lectus vestibulum. Lectus urna duis convallis convallis tellus id interdum velit. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat. Pellentesque adipiscing commodo elit at imperdiet dui accumsan. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Sed elementum tempus egestas sed sed risus pretium. Lacus viverra vitae congue eu consequat ac felis. Adipiscing tristique risus nec feugiat.",    
    "Maecenas accumsan lacus vel facilisis volutpat. Lectus magna fringilla urna porttitor rhoncus dolor. Amet mattis vulputate enim nulla aliquet. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Sed elementum tempus egestas sed sed. Turpis nunc eget lorem dolor sed. Duis ut diam quam nulla porttitor massa id neque. Mauris in aliquam sem fringilla ut morbi tincidunt augue. Tempus iaculis urna id volutpat lacus. Consectetur purus ut faucibus pulvinar elementum integer enim. Dictum at tempor commodo ullamcorper a lacus vestibulum. Massa eget egestas purus viverra accumsan in nisl. Non diam phasellus vestibulum lorem. Eget est lorem ipsum dolor. Nunc consequat interdum varius sit amet mattis. Consequat semper viverra nam libero justo laoreet. Ullamcorper malesuada proin libero nunc consequat interdum varius sit amet. Convallis posuere morbi leo urna molestie at.",   
    "In dictum non consectetur a erat nam at lectus urna. Enim nec dui nunc mattis enim ut. Ut placerat orci nulla pellentesque dignissim enim sit. Eu sem integer vitae justo eget magna fermentum. Erat velit scelerisque in dictum non consectetur. Sed odio morbi quis commodo odio aenean. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Lectus vestibulum mattis ullamcorper velit sed. Sagittis purus sit amet volutpat. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Vitae elementum curabitur vitae nunc sed velit dignissim sodales. Id diam maecenas ultricies mi eget mauris pharetra et. Purus sit amet luctus venenatis lectus magna fringilla. Pharetra convallis posuere morbi leo urna. Rhoncus dolor purus non enim praesent elementum. Nec tincidunt praesent semper feugiat nibh sed pulvinar. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Cras tincidunt lobortis feugiat vivamus. In ornare quam viverra orci.",    
    "Sit amet nisl purus in mollis nunc sed id. Neque gravida in fermentum et. Et netus et malesuada fames ac. Donec adipiscing tristique risus nec feugiat in fermentum posuere. Turpis egestas integer eget aliquet nibh. Eget duis at tellus at urna condimentum mattis pellentesque. Sed cras ornare arcu dui vivamus arcu felis bibendum ut. Risus feugiat in ante metus dictum at. Aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Volutpat lacus laoreet non curabitur gravida arcu ac tortor dignissim. Est ultricies integer quis auctor elit sed vulputate mi sit. Consequat nisl vel pretium lectus quam. Vestibulum sed arcu non odio euismod lacinia. Sit amet luctus venenatis lectus. Sodales ut eu sem integer vitae justo eget magna. Ac feugiat sed lectus vestibulum mattis. Elementum integer enim neque volutpat. Ante metus dictum at tempor commodo ullamcorper a lacus. Ornare arcu dui vivamus arcu felis bibendum. Et malesuada fames ac turpis egestas integer eget aliquet.",    
    "Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Sapien et ligula ullamcorper malesuada. Integer enim neque volutpat ac tincidunt. Neque aliquam vestibulum morbi blandit cursus risus at ultrices. At erat pellentesque adipiscing commodo elit at. Neque vitae tempus quam pellentesque nec nam aliquam. Mus mauris vitae ultricies leo integer. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Id porta nibh venenatis cras sed felis. Sem fringilla ut morbi tincidunt augue. Maecenas pharetra convallis posuere morbi. Lectus arcu bibendum at varius. Lorem dolor sed viverra ipsum nunc. Cum sociis natoque penatibus et. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis.",   
    "Ultricies integer quis auctor elit sed vulputate mi. Varius morbi enim nunc faucibus a. Tristique senectus et netus et malesuada fames ac turpis egestas. Sit amet luctus venenatis lectus magna. Augue lacus viverra vitae congue eu consequat ac felis donec. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Libero nunc consequat interdum varius sit. Orci eu lobortis elementum nibh tellus molestie. In fermentum et sollicitudin ac orci. Tincidunt arcu non sodales neque sodales ut etiam sit. Libero justo laoreet sit amet. Orci sagittis eu volutpat odio facilisis mauris sit amet. Sed vulputate mi sit amet mauris commodo quis imperdiet massa. Hendrerit gravida rutrum quisque non tellus orci. Hendrerit gravida rutrum quisque non tellus.",   
    "Velit euismod in pellentesque massa placerat duis. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis. Donec adipiscing tristique risus nec. Urna porttitor rhoncus dolor purus non enim praesent elementum facilisis. Scelerisque eleifend donec pretium vulputate. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Nisl tincidunt eget nullam non nisi. Pellentesque diam volutpat commodo sed egestas. Lorem ipsum dolor sit amet consectetur. Non diam phasellus vestibulum lorem sed risus ultricies tristique.",    
    "Pretium nibh ipsum consequat nisl vel pretium lectus. A iaculis at erat pellentesque adipiscing commodo elit at. Bibendum arcu vitae elementum curabitur vitae nunc sed velit dignissim. Integer quis auctor elit sed. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Arcu risus quis varius quam. Hac habitasse platea dictumst quisque sagittis. Eget mauris pharetra et ultrices neque ornare aenean euismod elementum. Sodales ut etiam sit amet. Enim diam vulputate ut pharetra sit amet aliquam id. Amet luctus venenatis lectus magna fringilla urna. Aliquam faucibus purus in massa tempor nec feugiat. Lectus proin nibh nisl condimentum id venenatis a. Rhoncus urna neque viverra justo nec ultrices dui. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Molestie at elementum eu facilisis sed. Morbi tristique senectus et netus et malesuada fames ac turpis. Magnis dis parturient montes nascetur ridiculus mus.",    
    "Ornare suspendisse sed nisi lacus sed. Magna fringilla urna porttitor rhoncus dolor purus. Et ligula ullamcorper malesuada proin libero nunc consequat. Neque laoreet suspendisse interdum consectetur libero id faucibus. Scelerisque eleifend donec pretium vulputate sapien nec. Felis donec et odio pellentesque diam volutpat commodo sed. Dignissim sodales ut eu sem integer vitae justo. Nam aliquam sem et tortor consequat id porta nibh. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Netus et malesuada fames ac turpis egestas integer eget. Mauris augue neque gravida in. Vulputate ut pharetra sit amet aliquam id diam. Lacinia at quis risus sed vulputate. Libero id faucibus nisl tincidunt eget nullam. Vitae sapien pellentesque habitant morbi tristique senectus. Ornare quam viverra orci sagittis eu. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Eros in cursus turpis massa tincidunt dui ut ornare. Eu volutpat odio facilisis mauris sit amet massa vitae.",   
    "Mauris pharetra et ultrices neque ornare aenean euismod elementum. Quis eleifend quam adipiscing vitae proin sagittis. Integer malesuada nunc vel risus commodo viverra. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Iaculis urna id volutpat lacus laoreet non curabitur gravida. Id venenatis a condimentum vitae sapien pellentesque habitant. At ultrices mi tempus imperdiet nulla malesuada. Id eu nisl nunc mi ipsum faucibus vitae. Sit amet nulla facilisi morbi. Est placerat in egestas erat imperdiet sed euismod nisi. Nibh tortor id aliquet lectus proin nibh nisl condimentum id. Eget arcu dictum varius duis at consectetur lorem. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Convallis a cras semper auctor neque vitae tempus.",   
    "A diam maecenas sed enim ut sem. Tortor dignissim convallis aenean et tortor at. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Dui accumsan sit amet nulla facilisi morbi tempus iaculis. Quisque sagittis purus sit amet volutpat. Urna duis convallis convallis tellus id interdum velit laoreet. Amet risus nullam eget felis eget nunc lobortis mattis. Tortor pretium viverra suspendisse potenti nullam ac tortor. Sed id semper risus in hendrerit. Massa vitae tortor condimentum lacinia quis vel eros.",   
    "Orci ac auctor augue mauris augue neque gravida. Pulvinar neque laoreet suspendisse interdum consectetur libero. Ut sem nulla pharetra diam sit amet nisl suscipit adipiscing. Ac odio tempor orci dapibus ultrices in iaculis nunc sed. Odio tempor orci dapibus ultrices. Parturient montes nascetur ridiculus mus mauris vitae ultricies. Pellentesque sit amet porttitor eget dolor morbi non arcu. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Dui sapien eget mi proin. Odio eu feugiat pretium nibh ipsum consequat. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. A scelerisque purus semper eget duis at. Pulvinar elementum integer enim neque volutpat ac tincidunt. Eget mi proin sed libero. Ullamcorper malesuada proin libero nunc. Varius vel pharetra vel turpis nunc eget. Ultrices neque ornare aenean euismod elementum nisi quis eleifend quam. Sodales ut etiam sit amet nisl purus in mollis."
  ];

  var paragraphs;

//funcao de salvar o texto se usuario colocar digitalo na pagina inicial
function saveText(){
    //salva em uma varialvel o valor inserido no campo de texto manualText
    var savingText = document.getElementById("manualText").value;
    //faz uma conferencia logica se existe algo escrito no campo e se não ele deixa a variavel paragraphs como o array randomP
    if (savingText === "") {
        paragraphs = randomP;
    } else {
        paragraphs = savingText.split(); 
    }
    //e por ultimo, se houver algum texto escrito no campo manualText ele o salva em paragraphs o transformando em um array para ser usado na funcao randomParagraph
}

//função para transição da tela de introdução do jogo, aonde podemos coloca o texto personalizado e a tela do game
function hideElement() { 
    // armazenamento de variaveis com o ID das divs que precisamos esconder com o elemento display none
    var intScreen = document.getElementById("intgame");
    var gameScreen = document.getElementById("game");
    if (intScreen.style.display === "none") {
        intScreen.style.display = "inline";
        gameScreen.style.display = "none";
    } else {
        intScreen.style.display = "none";
        gameScreen.style.display = "inline";
    }
}
